### ISSUE TITLE
csc g930fvfg1dqe3

### ISSUE THREAD

**Issue by peturbg** [GrifoDev/SuperKernel#11]
hi

i see you have problems with the peoples. So i updated to the latest samsung s7 vodafone spain and what is see it works wike charm, where i phone info that firware was with vodafone germany, so i try csc the latest and you Tkkg1994 has a problem that didn't make version history and when peoples install csc for vodafone spain it install the vodafone germany and some other version that don't work so i had to reinstall all my phone becouse of you. Tkkg1994 now again i restore my phone and when i update to latest operation system it is the same i use flashfire with spanish vodafone version and when it restore it get germany active csc germany i try with csc and home_csc. Tkkg1994 you have very big problems. i try write you in lg@linux.com and it comment your email don't exist. Tkkg1994 i can't restore and wait 1 month when you return to comment me. Tkkg1994 you are disorganized, why don't you restore your mobile phone and use false csc operatorl. You are in italy so use csc for vodafone spain, and you will be it will be germany. Tkkg1994 in every new version of csc you have to put the old csc for all operators becouse if you put only new and when some person restore csc and use your version 2.4.0 he will get another csc with old version. Tkkg1994 now how im gonna change country csc, i'm gonna change csc country and i will not tell how.

**Comment by Tkkg1994** [comment]
@peturbg I really don't understand your problem. I'm just getting back from my holidays seeing this on my github wall.. 

First: there is a specific csc github: https://github.com/GrifoDev/CSC
Second: You can choose VD2 and then inside that you will be asked to install a specific country csc (which includes the whole multi csc from all vodafone carriers and installs yours as default)
ThIrd: please use github for kernel related issues as this is a kernel git and not something else
Forth: you can always contact me on xda or grifodev
Fith: I really don't understand your language and what you are trying to tell me.. sorry
