### ISSUE TITLE
Wifi lost upon reboot.

### ISSUE THREAD

**Issue by maedot-d** [GrifoDev/SuperKernel#2]
Hi Luca,

Thanks for the new source code. I have built it and ran it on my S7 Edge. It works better than the earlier version when it comes to lags, but I have problem with wifi. It keeps wifi off each time I reboot it and forgets the saved passwords for the access points (I have to enable wifi and connect manually every time). Any ideas why this is so?

Maedot

**Comment by Tkkg1994** [comment]
You need to set ro.secure.storage to flase instead of true

**Comment by maedot-d** [comment]
Thanks for the quick response, set the ro.secure.storage=0 inside the ramdisk default.prop file and made new flashable zip. But same thing, wifi keeps getting lost.

**Comment by Tkkg1994** [comment]
Not 0, false

**Comment by maedot-d** [comment]
The ro.securestorage.support=false did the trick, it was somehow missing from my newly unpacked boot.img.
One more issue I see is the SD card (Transcend premium 300x 64GB ). It reports that the card is corrupt, even if it is visible and working when I am in the recovery mode. Reformatting it also does not help. The card works well in stock.

**Comment by Tkkg1994** [comment]
You have to make some ramdisk edits. Why don't you just use mine instead? I mean it would fully work then

**Comment by maedot-d** [comment]
That works also. The thing is after I do a couple of builds (I am playing around with tcp), I get a kernel that just boot loops and I need to do fresh ramdisk unpack. Now I have kept a working one to reuse for such cases.

**Comment by Tkkg1994** [comment]
well then adapt my changes to your ramdisk
