### ISSUE TITLE
Corrupted SD card.

### ISSUE THREAD

**Issue by maedot-d** [GrifoDev/SuperKernel#4]
Hi Luca,
S7 Edge still reports that the SD card is corrupt at all times, even after proposed reformatting. The card is visible and working on recovery mode. I have also tried your flashable image, with no avail. Do you have any tips on how to fix this issue?

**Comment by Tkkg1994** [comment]
I have had one time when this error appears, I had to rebooted my phone (from recovery mode) while connected to PC, then this happened. I just unplugged the phone and rebooted again, no more SD problem
