### ISSUE TITLE
May I ask a question?

### ISSUE THREAD

**Issue by wsz2074480** [GrifoDev/SuperKernel#5]
The maximum GPU clock is 650Mhz，I can not pull it up to 806Mhz. why?  Thank you for your wonderful kernel :) .

**Comment by wsz2074480** [comment]
Oh, it's V1.9.7 running in my G935FD.

**Comment by Tkkg1994** [comment]
You are using synapse to raise max freq?
I recommend to update to V2.0 since I won't update MM version (dead end)

**Comment by wsz2074480** [comment]
@Tkkg1994 
Thank you for your reply. The problem have been sloved since I installed synapse. I don't want to update to 7.0 because the Xposed framework haven't adapt to 7.0 yet. 
Sorry for my poor English.   lol

**Comment by Tkkg1994** [comment]
Okay so we can close this issue, Xposed will take time but I'm sure it will arrive in some months
